name: Jenkins Plugin
markdown: redcarpet
highlighter: pygments
github: https://github.com/mike-rogers/rally-bookkeeper
baseurl: /rally-bookkeeper

exclude: ["work"]

urls:
  - text: github
    url: https://github.com/mike-rogers/rally-bookkeeper
  - text: issues
    url: https://github.com/mike-rogers/rally-bookkeeper/issues
  - text: jenkins ci
    url: https://jenkins-ci.org
  - text: rally dev
    url: https://www.rallydev.com
